apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodemgrs.rafabsb.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: rafabsb.com
  names:
    kind: Nodemgr
    listKind: NodemgrList
    plural: nodemgrs
    singular: nodemgr
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Nodemgr is the Schema for the nodemgrs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NodemgrSpec defines the desired state of Nodemgr
          properties:
            annotations:
              description: NodemgrAnnotations define the annotations that must be
                a valid json.
              properties:
                lb:
                  items:
                    description: NodemgrLB defines a LB that points to the node.
                    properties:
                      dns:
                        type: string
                      instances:
                        items:
                          description: NodemgrLBInstances instances of a LB.
                          properties:
                            ip:
                              type: string
                            localport:
                              items:
                                format: int32
                                type: integer
                              type: array
                            name:
                              type: string
                            network:
                              type: string
                            site:
                              type: string
                            type:
                              type: string
                          required:
                          - ip
                          - localport
                          - name
                          - network
                          - site
                          - type
                          type: object
                        type: array
                      name:
                        type: string
                    required:
                    - dns
                    - instances
                    - name
                    type: object
                  type: array
              type: object
            labels:
              additionalProperties:
                type: string
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: object
            taints:
              items:
                description: NodemgrTaint defines the Taint that a node has.
                properties:
                  effect:
                    type: string
                  key:
                    type: string
                  value:
                    type: string
                required:
                - effect
                - key
                - value
                type: object
              type: array
          required:
          - labels
          type: object
        status:
          description: NodemgrStatus defines the observed state of Nodemgr
          properties:
            phase:
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
